baseURL: "https://multiplylabs.io/"
languageCode: "en-us"
title: "Multiply"
permalinks:
  post: /:title/
taxonomies:
  category: "categories"
  tag: "tags"
paginate: 10
pygmentsOptions:
  noclasses: true
pygmentsUseClasses: false
PygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "manni"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
author:
    name: "AenTan"
    email: "hello@aentan.com"